apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-51rz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-igil-tenant/rhtap-demo-app/hacbs-test-project-51rz@sha256:01cd3be48c556650e3da377088d7d49f6456a6a039ce79acef2893107d049afb
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
